### ISSUE TITLE
Uncaught Error: Cannot find module '../service/undefined'

### ISSUE THREAD

**Issue by hevisko** [ayurmedia/atom-sync-cygwin#14]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-sync-cygwin](https://github.com/ayurmedia/atom-sync-cygwin) package 0.10.0

### Stack Trace

Uncaught Error: Cannot find module '../service/undefined'

```
At module.js:545

Error: Cannot find module '../service/undefined'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at Object.sync (/packages/atom-sync-cygwin/lib/controller/service-controller.coffee:115:6)
    at Object.onSync (/packages/atom-sync-cygwin/lib/controller/service-controller.coffee:66:12)
    at /packages/atom-sync-cygwin/lib/atom-sync-cygwin.coffee:27:19)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:694361)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:701828)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:20.4.0 atom-sync-cygwin:download-directory (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
ansible-galaxy 0.2.1 
ansible-snippets 0.2.0 
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-sync-cygwin 0.10.0 
atomatigit 1.5.5 
batman-syntax 1.1.0 
blue-dream-ui 0.35.0 
build-ocaml 0.2.2 
busy-signal 2.0.1 
carbon-blue-atom 2.1.1 
compare-files 0.8.1 
coral-blue-syntax 0.2.0 
duotone-blue-dark-syntax 1.4.0 
git-add 0.0.0 
git-clone 0.2.0 
git-control 0.9.0 
git-go 1.0.5 
git-history 3.3.0 
git-log 0.4.1 
git-plus 8.6.2 
git-status 0.3.4 
git-wip 0.3.0 
gruvbox-mellow 0.2.0 
hyperclick 0.1.5 
intentions 1.1.5 
language-ansible 0.2.2 
language-diff 0.7.0 
language-ocaml 1.9.5 
language-ocaml-fix 3.3.0 
linter 2.3.0 
linter-ocaml 1.2.0 
linter-pylama 0.10.1 
linter-pylint 2.1.1 
linter-python 3.1.2 
linter-ui-default 1.7.1 
markdown-preview-plus 3.8.0 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-cursorline 0.2.0 
nucleus-dark-ui 0.12.3 
ocaml-indent 0.7.1 
ocaml-merlin 0.14.7 
ocaml-repl 0.7.2 
open-git-modified-files 0.2.4 
remote-atom 1.3.12 
remote-atom-plus 0.1.0 
remote-edit 1.9.0 
sync-settings 0.8.6 
tabs-closer 0.16.0 
tomorrow-night-blue-syntax 0.1.0 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.2 
vim-mode 0.66.0 
vnc 0.1.4 
Watchmenesque-Dark 0.14.0 
```

**Comment by ayurmedia** [comment]
hi, probably atom core changed the apis, so the plugin breaks. 
i don't support the plugin anymore as i stated in the readme of this github project, 
software is "as is". 

i am using phpstorm now, which is superior with code complete and other stuff and its inefficient to use atom. 

if you fix it and make a pull request i can merge it.

**Comment by hevisko** [comment]
okay, missed that, as I haven't (actively) used it from remote->local sync in quite awhile (the local->remote still seems to work okay), and the "create a support ticket" buttn created the ticket sorta "on my behalf" 😁 

time to research another IDE that works nice with Ansible, yaml, bash etc. like I got used to in Atom.. but yeah, it's been a pain this constant package breakages

**Comment by ayurmedia** [comment]
what about visual studio code from microsoft, seems similar to atom, also has plugins. 
https://code.visualstudio.com/
