### ISSUE TITLE
Uncaught TypeError: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by spartida-iteso** [ayurmedia/atom-sync-cygwin#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-sync-cygwin](https://github.com/ayurmedia/atom-sync-cygwin) package 0.10.0

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:105

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.normalize (path.js:263:5)
    at Object.onSync (/packages/atom-sync-cygwin/lib/controller/service-controller.coffee:38:16)
    at /packages/atom-sync-cygwin/lib/atom-sync-cygwin.coffee:42:21)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:349576)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1242036)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:1238170)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:284782)
```

### Commands

```
     -7:25.6.0 intentions:highlight (input.hidden-input)
     -7:25.3.0 core:paste (input.hidden-input)
     -7:23.4.0 intentions:highlight (input.hidden-input)
     -7:23 core:paste (input.hidden-input)
     -7:22.5.0 core:save (input.hidden-input)
 70x -6:58.1.0 intentions:highlight (input.hidden-input)
     -6:49.2.0 atom-sync:sync-up (input.hidden-input)
  5x -6:45 intentions:highlight (input.hidden-input)
     -6:40.5.0 atom-sync:sync-up (input.hidden-input)
  8x -4:34.1.0 core:backspace (input.hidden-input)
  2x -3:04.3.0 intentions:highlight (input.hidden-input)
     -0:36 atom-sync:sync-up (input.hidden-input)
  2x -0:33 intentions:highlight (input.hidden-input)
  2x -0:17.8.0 atom-sync:sync-up (input.hidden-input)
     -0:02.5.0 intentions:highlight (input.hidden-input)
     -0:02.3.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-npm 0.3.1 
atom-sync-cygwin 0.10.0 
autocomplete-robot-framework 3.6.0 
busy-signal 2.0.1 
file-icons 2.1.33 
highlight-selected 0.16.0 
intentions 1.1.5 
language-csv 1.1.2 
language-cypher 0.5.0 
language-robot-framework 2.4.0 
linter 2.3.0 
linter-pylint 2.1.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
multiline-select 1.8.2 
npm 2.0.0 
npm-install 4.0.4 
pretty-json 2.1.2 
rainbow-csv 1.4.0 
tablr 1.8.3 
test 0.1.2 
```

**Comment by ayurmedia** [comment]
Hi, i moved on to use PHPStorm now, and don't use or maintain atom.io anymore. 
If you write a patch and do a pull request i can update this github project. 
My guess is that the API of atom.io has changed. and now the path argument is different and needs to be changed in the plugin code.
